services:
  ## Databases
  wallet-db:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet
    ports:
      - 35432:5432

  member-service-db:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: member-service
    ports:
      - 15432:5432

  ## Broker
  broker:
    image: apache/kafka:latest
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # 1. Definimos os nomes dos Listeners
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      # 2. Onde o Kafka vai "ouvir" (bind)
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093'
      # 3. O que o Kafka vai "anunciar" para os clientes
      # Redpanda recebe 'broker:9092' | Sua App externa recebe 'localhost:29092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://broker:9092,EXTERNAL://localhost:29092'
      # 4. Define qual listener os brokers usam entre si
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "29092:29092" # Porta para sua aplicação externa
      # - "9092:9092" # Opcional, se quiser expor a interna também
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server localhost:9092 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  broker-console:
    image: docker.redpanda.com/redpandadata/console:latest
    environment:
      KAFKA_BROKERS: broker:9092
    ports:
      - "8080:8080"
    depends_on:
      broker:
        condition: service_healthy

  ## Observabilidade
  otel-lgtm:
    image: grafana/otel-lgtm
    ports:
      - 3000:3000
      - 4317:4317
