services:
  wallet-db:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet
    ports:
      - 35432:5432

  member-service-db:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: member-service
    ports:
      - 15432:5432

  otel-lgtm:
    image: grafana/otel-lgtm
    ports:
      - 3000:3000
      - 4317:4317
