apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet
  namespace: tellawl
  labels:
    app: wallet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wallet
  template:
    metadata:
      labels:
        app: wallet
    spec:
      containers:
        - name: wallet
          image: lopesgabriel/wallet:1.0.0
          env:
            - name: VERSION
              value: "1.0.0"
            - name: LOG_LEVEL
              value: "INFO"
            - name: OTEL_COLLECTOR_URL
              value: "192.168.1.21:4317"
            - name: MEMBER_SERVICE_URL
              value: "http://member-service.tellawl.svc.cluster.local:8080"
            - name: POSTGRESQL_URL
              valueFrom:
                secretKeyRef:
                  name: wallet-db-secret
                  key: POSTGRESQL_URL
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"

---

apiVersion: v1
kind: Service
metadata:
  name: wallet
  namespace: tellawl
  labels:
    app: wallet
spec:
  type: ClusterIP
  selector:
    app: wallet
  ports:
    - name: http
      port: 8080
      targetPort: 8080
