apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  namespace: tellawl
  labels:
    app: notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
        - name: notifier
          image: lopesgabriel/notifier:91c1f45-arm64
          env:
            - name: SERVICE_VERSION
              value: "1.0.0"
            - name: LOG_LEVEL
              value: "INFO"
            - name: OTEL_COLLECTOR_ENDPOINT
              value: "172.31.40.229:4317"
            - name: KAFKA_BROKERS
              value: "172.31.40.229:9092"
            - name: KAFKA_TOPIC
              value: "wallet"
            - name: GOOGLE_OAUTH_CREDENTIALS_FILE
              value: "/etc/notifier/credentials/credentials.json"
            - name: GOOGLE_SERVICE_CREDENTIALS_FILE
              value: "/etc/notifier/credentials/service-credentials.json"
            - name: GOOGLE_TOKEN_FILE
              value: "/etc/notifier/credentials/token.json"
            - name: POSTGRESQL_URL
              valueFrom:
                secretKeyRef:
                  name: notifier-db-secret
                  key: POSTGRESQL_URL
            - name: GOOGLE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: notifier-secret
                  key: GOOGLE_PROJECT_ID
            - name: PUBSUB_TOPIC
              valueFrom:
                secretKeyRef:
                  name: notifier-secret
                  key: PUBSUB_TOPIC
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: notifier-secret
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: notifier-secret
                  key: SMTP_PORT
            - name: SMTP_FROM
              valueFrom:
                secretKeyRef:
                  name: notifier-secret
                  key: SMTP_FROM
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notifier-secret
                  key: SMTP_PASSWORD
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - name: google-credentials
              mountPath: /etc/notifier/credentials
              readOnly: true
      volumes:
        - name: google-credentials
          secret:
            secretName: notifier-credentials

---

apiVersion: v1
kind: Service
metadata:
  name: notifier
  namespace: tellawl
  labels:
    app: notifier
spec:
  type: ClusterIP
  selector:
    app: notifier
  ports:
    - name: http
      port: 8080
      targetPort: 8080
